apiVersion: apps/v1
kind: Deployment
metadata:
  name: websample
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: websample
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: websample
    spec:
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: websample
          image: websample
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 100mm
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: edi-worker-secret
            - configMapRef:
                name: edi-worker-configmap