apiVersion: v1
kind: Service
metadata:
  name: websample-svc
  labels:
    metrics: prometheus
spec:
  type: ClusterIP
  selector:
    app: websample
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
